/*
    记录某一个房间晚间所做的操作信息
*/
const db = require('./db.js');
Schema = db.Schema;
const actionSchema = new Schema(
    {
        roomNumber: String, //房间号
        nightInfo: Array,//夜晚操作，数组从第一个夜间开始对应数组
        // first: Object,//第一个夜晚的操作
        // second: Object,//第二个...
        // third: Object,//第三个...
        // forth: Object,//第四个...
        // fifth: Object,//第五个...
        // sixth: Object,//第六个...
        // seventh: Object,//第七个...
        // eighth: Object,//第八个...
        // ninth: Object,//第九个...
        // tenth: Object,//第十个...
        // eleventh: Object,//第十一个...
        // twelfth: Object,//第十二个...
        // thirteenth: Object,//第十三个...
        /**
         * 每个夜晚是个对象
         */
    }, {
        timestamps: true,
        toJSON: { virtuals: true },
        toObject: { virtuals: true },
    }
);
module.exports = db.model('action', actionSchema);
